volumes:
  grafana:
  loki_data:
  alloy_data:

services:
  app:
    # image: alakaganaguathoork/local-business:latest
    container_name: local-business
    restart: unless-stopped
    build:
      dockerfile: Dockerfile
    volumes:
      - ./app/:/app
    # user: "${UID:-0}:${GID:-0}" # not relevant - Dockerfile itself was fixed
    env_file: 
     - path: ./app/.env
       required: true
    ports: 
      - "5400:5400"
    labels:
    - logs=enable
  
  database:
    image: mysql
    container_name: db-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      # MYSQL_USER: admin   # no users yet
      # MYSQL_PASSWORD: admin 
    volumes:
      - ./app/db/sql/plain/init_db/:/docker-entrypoint-initdb.d/
    ports:
      - 3306:3306

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./monitoring/prometheus/prometheus.rules.yml:/etc/prometheus/prometheus.rules.yml
      - ./monitoring/prometheus/targets.yml:/etc/prometheus/targets/internal_monitoring_targets.yml
      - .docker/prometheus_data:/prometheus
    user: "${UID:-0}:${GID:-0}"
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.console.libraries=/etc/prometheus/console_libraries
      - --web.console.templates=/etc/prometheus/consoles
      - --web.enable-lifecycle
    ports:
      - "9090:9090"
  
  alertmanager:
    image: prom/alertmanager
    container_name: alert_manager
    restart: unless-stopped
    depends_on:
      - prometheus
    command: 
      - --config.file=/etc/alertmanager/alertmanager.yml
      - --log.level=debug
    volumes:
      - ./monitoring/alertmanager/generated/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    ports:
      - "9093:9093"
   
  node-exporter:
    image: prom/node-exporter
    container_name: node_exporter
    depends_on:
      - prometheus
    command: 
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--path.rootfs=/rootfs'
    pid: host 
    restart: unless-stopped
    volumes:
      - '/proc:/host/proc:ro,rslave'
      - '/sys:/host/sys:ro,rslave'
      - '/:/rootfs:ro,rslave'
    network_mode: host
    expose:
      - 9100

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    environment:
      - GF_LOG_LEVEL=debug
      - GF_METRICS_ENABLED=true
      - GF_AUTH_ENABLED=false
    volumes:
      - grafana:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards
    user: "${UID:-0}:${GID:-0}"
    # user: "472:472" # less privileged (from docs)
    ports:
      - 3000:3000
  
  loki:
    image: grafana/loki:latest
    container_name: loki
    command: ["-config.file=/etc/loki/config.yaml", "-config.expand-env=true"]
    volumes:
      - ./monitoring/loki/config/config.yaml:/etc/loki/config.yaml
      - loki_data:/loki
    restart: unless-stopped
    ports:
      - 3100:3100
  
  alloy:
    image: grafana/alloy:latest
    container_name: alloy
    hostname: halloy
    restart: unless-stopped
    ports:
      - 12345:12345
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./monitoring/alloy/config/config.alloy:/etc/alloy/config.alloy
      - alloy_data:/var/lib/alloy/data
    command: >
      run
      --server.http.listen-addr=0.0.0.0:12345
      --storage.path=/var/lib/alloy/data
      /etc/alloy
    depends_on:
      - loki
    labels:
    - "alloy.logs.enable=true"
    
  # Example I found online for future
  # gateway:
  #   image: nginx:latest
  #   depends_on:
  #     - read
  #     - write
  #   entrypoint:
  #     - sh
  #     - -euc
  #     - |
  #       cat <<EOF > /etc/nginx/nginx.conf
  #       user  nginx;
  #       worker_processes  16;  ## Default: 1
  #       events {
  #         worker_connections   1000;
  #       }
  #       http {
  #         resolver 127.0.0.11;
  #         server {
  #           listen             3100;
  #           location = / {
  #             return 200 'OK';
  #             auth_basic off;
  #           }
  #           location = /api/prom/push {
  #             proxy_pass       http://write:3100\$$request_uri;
  #           }
  #           location = /api/prom/tail {
  #             proxy_pass       http://read:3100\$$request_uri;
  #             proxy_set_header Upgrade \$$http_upgrade;
  #             proxy_set_header Connection "upgrade";
  #           }
  #           location ~ /api/prom/.* {
  #             proxy_pass       http://read:3100\$$request_uri;
  #           }
  #           location = /loki/api/v1/push {
  #             proxy_pass       http://write:3100\$$request_uri;
  #           }
  #           location = /loki/api/v1/tail {
  #             proxy_pass       http://read:3100\$$request_uri;
  #             proxy_set_header Upgrade \$$http_upgrade;
  #             proxy_set_header Connection "upgrade";
  #           }
  #           location ~ /loki/api/.* {
  #             proxy_pass       http://read:3100\$$request_uri;
  #           }
  #         }
  #       }
  #       EOF
  #       /docker-entrypoint.sh nginx -g "daemon off;"
  #   ports:
  #     - "3100:3100"
  #   networks:
  #     - loki